apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: expose-app
  namespace: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/shared-gateway-x
  http:
  - match:
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
